### PR TITLE
Fix new year ArgumentOutOfRangeException in facebook's posts

### PR DESCRIPTION
**Pull request by rwojcik**
Since there are no posts yet for facebook in this year ([http://netdevelopers.pl/facebook/top-current-year](http://netdevelopers.pl/facebook/top-current-year)) server currently throws an exception System.ArgumentOutOfRangeException in HLListPage.cs:25. I've decided not to use this class (sorry  @pawelklimczyk :D), change this to List<> and prompt user that there are no posts found.

### CODE REVIEW

**Comment by pawlos** [comment]
@rwojcik it looks like it doesn't build. Check the AppVeyor logs

**Comment by pawelklimczyk** [comment]
I will fix that in HandyLib. HLListPage was introduced because it has build-in pagination mechanism...
I will fix that tomorrow...

**Comment by rwojcik** [comment]
Well, if it's going to be fixed in HLListPage then there is no point in keeping this PR

**Comment by pawelklimczyk** [comment]
Part of it was fixed in HLListPage
whole fix is here:
https://github.com/NetDevelopersPoland/NetDevPLWebsite/commit/97508f3dc006d1a61b94d248ec21a5ee1931972a

**Pull request closed without merging**
