### PR TITLE
Initializing logger every time is unnecessary

### PR DESCRIPTION
**Pull request by dario-l**
GetCurrentClassLogger is not performant and should be cached

### CODE REVIEW

**Comment by pawlos** [comment]
@dario-l , @pawelklimczyk I think both implementation are very strange. I think the idea behind NLog.LogManager.GetCurrentClassLogger is to have such object (I agree it should be static) in a class where the logging takes place - then you can nicely filter those logs in a config file. Right now all the logs comes from one class so it's impossible to filter based on class.

**Comment by dario-l** [comment]
@pawlos You are right but this is another story.

**Comment by pawlos** [comment]
@dario-l ok :)

**Comment by pawelklimczyk** [comment]
the idea here is to have something in the first place.

**Pull request merged**
